yii/models/Cikkek.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\SluggableBehavior;


/**
 * This is the model class for table "cikkek".
 *
 * @property int $id
 * @property string $cim
 * @property string $link
 * @property string $meta_txt
 * @property string $meta_keys
 * @property string $text
 * @property int $created_by
 */
class Cikkek extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'cikkek';
    }


    public function behaviors()
    {
        return [
            // timestamp is lehetne akár
            [
            'class' => SluggableBehavior::class,
            'slugAttribute' => 'link',
            'attribute' => 'cim'
            ]
        ];
    }


    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['cim', 'meta_txt', 'meta_keys', 'text', 'created_by'], 'required'],   // 'link', automatára inkább
            [['text'], 'string'],
            [['created_by'], 'integer'],
            [['cim', 'link', 'meta_txt', 'meta_keys'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'cim' => 'Cim',
            'link' => 'Link',
            'meta_txt' => 'Meta Txt',
            'meta_keys' => 'Meta Keys',
            'text' => 'Text',
            'created_by' => 'Created By',
        ];
    }

    /**
     * @return \yii\db\ActiveWuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }


    public function getEncodedBody()
    {
        return \yii\helpers\HtmlPurifier::process($this->text);
    }
}

yii/controllers/CikkekController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Cikkek;
use app\models\CikkekSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CikkekController implements the CRUD actions for Cikkek model.
 */
class CikkekController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Cikkek models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CikkekSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Cikkek model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($link) // id
    {
        return $this->render('view', [
            'model' => $this->findModel($link), // id
        ]);
    }

    /**
     * Creates a new Cikkek model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Cikkek();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'link' => $model->link]);           // ['view', 'id' => $model->id]
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Cikkek model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($link)     // id
    {
        $model = $this->findModel($link);   // id

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'link' => $model->link]);               // ['view', 'id' => $model->id]
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Cikkek model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($link) // id
    {
        $this->findModel($link)->delete();  //id

        return $this->redirect(['index']);
    }

    /**
     * Finds the Cikkek model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Cikkek the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($link)// id
    {
        if (($model = Cikkek::findOne(['link' => $link])) !== null) {  // ($id)
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

yii/views/cikkek/_cikkek_item.php
<?php
/**
 * Created by PhpStorm.
 * User: szaboszabolcs
 * Date: 2021. 03. 18.
 * Time: 20:54
 */
/** @var $model \app\models\Cikkek */
?>

<div>
    <a href="<?php echo \yii\helpers\Url::to(['/cikkek/view', 'link' => $model->link]); ?>" >      <!-- ['/article/view', 'id' => $model->id] -->
        <h3> <?php echo \yii\helpers\Html::encode($model->cim) ?> </h3>
    </a>
    <div>
<!--        <?php //echo \yii\helpers\HtmlPurifier::process($model->text) ?> -->
        <?php echo \yii\helpers\StringHelper::truncateWords($model->getEncodedBody(), 80) ?>
        <hr />
<!--        <p>--><?php //echo \yii\helpers\Html::encode(implode(', ', $model->meta_keys)) ?><!--</p>-->
        <p><?php echo "<strong>Keywords: </strong>" . \yii\helpers\Html::encode($model->meta_keys) ?></p>
        <hr />
    </div>
</div>

yii/views/cikkek/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\ckeditor\CKEditor;


/* @var $this yii\web\View */
/* @var $model app\models\Cikkek */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="article-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'cim')->textInput(['maxlength' => true])->label('Cím') ?>

    <?= $form->field($model, 'link')->textInput(['maxlength' => true])->label('Link (automata html-barát)') ?>

    <?= $form->field($model, 'meta_txt')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'meta_keys')->textInput(['maxlength' => true]) ?>

<!--    <?//= $form->field($model, 'text')->textarea(['rows' => 6]) ?> -->
    <?= $form->field($model, 'text')->widget(CKEditor::className(),
        [
            'kcfinder' => true,
            'kcfOptions' => [
//                'uploadURL' => '@web/upload',
//                'uploadDir' => '@webroot/upload',
                'uploadURL' => Yii::getAlias('@web').'/upload',
                'uploadDir' => Yii::getAlias('@webroot').'/upload',
                ],
//            'options' => ['rows' => 30],
            'clientOptions' => ['height' => 500],
            'preset' => 'basic'
            ])
    ?>

    <?php $usermost = Yii::$app->user->identity->id ?>    <!-- Yii::$app->user->identity->username -->

    <?= $form->field($model, 'created_by')->textInput(['value' => $usermost])->label('Created by (automata user id)') ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

yii/views/cikkek/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\CikkekSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="article-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'cim') ?>

    <?= $form->field($model, 'link') ?>

    <?= $form->field($model, 'meta_txt') ?>

    <?= $form->field($model, 'meta_keys') ?>

    <?php // echo $form->field($model, 'text') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

yii/views/cikkek/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Cikkek */

$this->title = 'Oldal létrehozása';
$this->params['breadcrumbs'][] = ['label' => 'Cikkek', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="article-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

yii/views/cikkek/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\grid\ListView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\CikkekSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
/** @var $model \app\models\Cikkek */

$this->title = 'Cikkek';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="article-index">

    <h1><?= Html::encode($this->title) ?></h1>



    <?php if (!Yii::$app->user->isGuest) : ?>
        <p>
            <?= Html::a('Új oldal létrehozása', ['create'], ['class' => 'btn btn-success']) ?>
        </p>
    <?php endif; ?>





    <?php if (!Yii::$app->user->isGuest) : ?>
        <?php Pjax::begin(); ?>
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,

            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                'id',
                'cim',
                'link',
                'meta_txt',
                'meta_keys',
                //'text:ntext',
                //'created_by',



                ['class' => 'yii\grid\ActionColumn',
                    'header' => 'Műveletek',
                    'headerOptions' => ['style' => 'color:#337ab7'],
                    'template' => '{view} {update} {delete}',

                    'buttons' => [
                        'view' => function ($url, $model) {
                            return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, [
                                'title' => Yii::t('app', 'Megnéz'),
                            ]);
                        },

                        'update' => function ($url, $model) {
                            return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                                'title' => Yii::t('app', 'Szerkeszt'),
                            ]);
                        },
                        'delete' => function ($url, $model) {
                            return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [

                                'data' => [
                                    'confirm' => 'Biztos, hogy törlöd ezt az elemet?',
                                    'method' => 'post',
                                ],
                            ]);
                        }

                    ],
                    'urlCreator' => function ($action, $model, $key, $index) {
                        if ($action === 'view') {
//                            $url ='index.php?r=client-login/lead-view&id='.$model->id;
                            $url ='/yii/web/cikkek/'.$model->link;
                            return $url;
                        }

                        if ($action === 'update') {
                            $url ='/yii/web/cikkek/update?link='.$model->link;
                            return $url;
                        }
                        if ($action === 'delete') {
                            $url ='/yii/web/cikkek/delete?link='.$model->link;
                            return $url;
                        }


                    }
                ],

            ],
        ]);
        ?>
        <?php Pjax::end(); ?>
    <?php else: ?>

    <?= \yii\widgets\ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => '_cikkek_item'
    ]);
    ?>
    <?php endif; ?>



</div>

yii/views/cikkek/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Cikkek */

$this->title = 'Oldal szerkesztése: ' . $model->link; // $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Cikkek', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->link, 'url' => ['view', 'link' => $model->link]]; // $model->id, 'url' =>['view', 'id' => $model->id
$this->params['breadcrumbs'][] = 'Update';

?>
<div class="article-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

yii/views/cikkek/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Cikkek */

$this->title = $model->cim; // id
$this->params['breadcrumbs'][] = ['label' => 'Cikkek', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="article-view">

    <h1><?= Html::encode($this->title) ?></h1>
    <p class="text-muted">
        <small> Felvitte (id): <?php echo $model->created_by; ?></small>
    </p>

    <?php if (!Yii::$app->user->isGuest) : ?>
        <p>
            <?= Html::a('Update', ['update', 'link' => $model->link], ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Delete', ['delete', 'link' => $model->link], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => 'Biztos, hogy törlöd ezt az elemet?',
                    'method' => 'post',
                ],
            ]) ?>
        </p>
    <?php endif; ?>

    <div>
        <?php echo $model->getEncodedBody(); ?>
    </div>
    <hr/>
    <p><?php echo "<strong>Keywords: </strong>" . \yii\helpers\Html::encode($model->meta_keys) ?></p>
    <hr/>

</div>